### ISSUE TITLE
shared hashes

### ISSUE THREAD

**Issue by vang1ong7ang** [vang1ong7ang/NE0FS#1]
welcome to share anything you uploaded to NE0FS.

:)

**Comment by vang1ong7ang** [comment]
`757747b2ba27f459f40d15cc6b295ae08b9d4c68ccd4db54b999f50f314f0d95`

**Comment by joeqian10** [comment]
ae5da8836de13b770568a48c345d4eb3ad2696c1175554717dcffb30d8bdbf49

**Comment by joeqian10** [comment]
`f043568c47a5d6e4a71e6f3f946cc2e08ca5b4b497fa0fa0f43a466c76d96da9`

**Comment by rev-chaos** [comment]
c8343a0c285243faf389cafe0f19cf1c696123915e90debab18ef45d103b8e79

**Comment by EdgeDLT** [comment]
`ea8fd48a94fe5473ff5b9449e5832fa791585ae6698eaaee1b077126f02784dd`

**Comment by vang1ong7ang** [comment]
@EdgeDLT I see dylan kkkkkkkk

**Comment by wulalablalbalba** [comment]
4c3483d7049a921fa12dba3ec05b5eec72ff365a111e76a522357944e3380103

**Comment by vang1ong7ang** [comment]
if you only have a hash without a filename/content-type, essentially you can guess the content type from the first 4 bytes of the downloaded file. for example, a `png` image may starts with the following data:

```
00000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR
00000010: 0000 01bd 0000 0226 0806 0000 00c7 6754  .......&......gT
```

#2 is proposed to add a metadata header transaction to describe extra information.

then you will never worry forgetting the name/type of the uploaded file.

**Comment by vang1ong7ang** [comment]
`neologo.svg`: `657bf34208e939390a91b429655a8b1c1257e5797422de5e740bbbc9ab32323e`

**Comment by vang1ong7ang** [comment]
`bc.mp4`: `8e764b0a466c41e27bad426c8651a89e93ab4be73ffa883b7aebd59ebb59a519`

**Comment by vang1ong7ang** [comment]
`ne0fs-gui,png`: `79a463bff921448f10953f63493e236851eb6007c52fcbd4c7b24fa43fef5ca4`

**Comment by joeqian10** [comment]
`b252ed1797e90563ee37cea7a8e343c6ab753a239ae45a8a20c31e51dc48e0b0`

**Comment by vang1ong7ang** [comment]
since NE0FS 0.2, NE0FS hashes are deprecated, use NE0FS links instead.

Then we move to #7
